name: Pull request
on:
  pull_request:
    branches: [main]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: make install-dev
      - name: Check formatting
        run: make lint

  Test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: make install-dev
      - name: Run tests
        run: make test
      - uses: codecov/codecov-action@v4
      - name: Build package
        run: make build
      - name: Test documentation builds
        if: matrix.os == 'ubuntu-latest'
        run: |
          make install-docs
          make docs
