name: Common CI Tasks

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Debug Info
        run: |
          python --version
          pip --version
          pwd
          ls -la
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e ".[dev]"
          pip freeze
          pip show requests
      - name: Check formatting
        run: make lint

  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Debug Info
        run: |
          python --version
          pip --version
          pwd
          ls -la
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e ".[dev]"
          pip freeze
          pip show requests
      - name: Run tests
        run: |
          python -c "import sys; print(sys.path)"
          python -c "import pippy; print(pippy.__file__)"
          python -m pytest tests/ --cov=pippy --cov-report=xml
      - uses: codecov/codecov-action@v4
      - name: Build package
        run: make build
