name: Main Branch CI/CD

on:
  push:
    branches: [main]

jobs:
  lint-and-test:
    uses: ./.github/workflows/common.yaml
    with:
      python-version: "3.12"

  deploy-docs:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          make install-dev
          make install-docs
      - name: Build docs
        run: make docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
